ALTER TABLE sessions ADD COLUMN IF NOT EXISTS n8n_workflow JSONB;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS n8n_template_name TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS n8n_generated_at TIMESTAMPTZ;
